CREATE TABLE `LOCK_UPDATE_BY_COUNTRY_ID` (
  `CountryID` varchar(100) NOT NULL,
  `LOCKED_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ROLLOUT_ID` int(11) NOT NULL,
  `planID` varchar(45) NOT NULL,
  PRIMARY KEY (`CountryID`,`planID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `PRICE_REVISION` (
  `ROLLOUTID` int(11) NOT NULL,
  `REVISION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COUNTRYID` varchar(45) DEFAULT NULL,
  `OLDPRICE` decimal(5,2) DEFAULT NULL,
  `NEWPRICE` decimal(5,2) DEFAULT NULL,
  `PLANID` varchar(45) DEFAULT NULL,
  `UPDATEDTIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`REVISION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
CREATE TABLE `ROLLOUT_STATUS` (
  `ROLLOUTID` int(11) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(45) DEFAULT NULL,
  `ERROR` varchar(255) DEFAULT NULL,
  `updatedTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ROLLOUTID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
CREATE TABLE `USER_PLAN` (
  `USERID` int(11) NOT NULL AUTO_INCREMENT,
  `COUNTRYID` varchar(100) NOT NULL,
  `PRICE` decimal(5,2) DEFAULT NULL,
  `PLANID` varchar(45) NOT NULL,
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB AUTO_INCREMENT=150001 DEFAULT CHARSET=utf8;
